services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - '5433:5432'
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - pg-network

  node-app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    command: npm run start:dev
    ports:
      - '8000:3000'
    networks:
      - pg-network
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./src:/app/src

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '6379:6379'
    networks:
      - pg-network
    volumes:
      - redis-data:/data

networks:
  pg-network:

volumes:
  pg-data:
  redis-data:
