services:   
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - pg-network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.pl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network

  node-app:
    build:
      context: . # Ścieżka do folderu z Dockerfile dla Node.js
      dockerfile: docker/node/Dockerfile
    ports:
      - '8000:3000'
    networks:
      - pg-network
    depends_on:
      - db
    env_file:
      - .env
  
networks:
  pg-network:

volumes:
  pg-data:
